services:
  - type: web
    name: gts-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: POSTGRES_DB
        fromDatabase:
          name: gts-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: gts-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: gts-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: gts-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: gts-db
          property: port

databases:
  - name: gts-db
    databaseName: gts
    user: gts_user
